#
# Makefile for libiberty under openVMS/AXP
#
# For use with gnu-make for vms
#
# Created by Klaus Kämpf, kkaempf@progis.de
#
#
CC=gcc

OBJS=bcopy.obj,bcmp.obj,getopt.obj,obstack.obj,xexit.obj,xmalloc.obj,hex.obj,\
   getopt1.obj,cplus-dem.obj,strncasecmp.obj,strcasecmp.obj,strdup.obj,\
   concat.obj,getruntime.obj,getpagesize.obj,alloca.obj,xstrerror.obj,\
   xstrdup.obj,xatexit.obj

ifeq ($(CC),gcc)
CFLAGS=/include=([],[-.include])
else
CFLAGS=/noopt/debug/include=([],[-.include])
endif

libiberty.olb: alloca-conf.h $(OBJS)
	purge
	lib/create libiberty *.obj

alloca-conf.h: alloca-norm.h
	$(CP) $< $@
