# Config for MkDocs
# To build:
# 1. Ensure you have MkDocs and friends: `pip install -e ".[docs]"`
# 2. `mkdocs serve` to view site locally with live refresh
# 3. `mkdocs build` to build the static site.
#    In the future, a GitHub action should do this.

site_name: CodeLLM-Devkit
repo_url: https://github.com/IBM/codellm-devkit
repo_name: IBM/codellm-devkit
# edit_uri: docs/
# site_url: https://ibm.github.io/cldk/

# This unusual configuration of docs/site directories
# is due to GitHub not presenting /site/ as an option
# when selecting the dir for Pages.
# docs_dir: docs
site_dir: _site

copyright: Copyright &copy; 2024 IBM

theme:
  name: material
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  icon:
    repo: fontawesome/brands/github
  features: # see https://squidfunk.github.io/mkdocs-material/setup/
    - search.highlight
    - search.suggest
    - navigation.sections
    - navigation.path
    - navigation.footer
    - navigation.indexes
    - navigation.top
    - toc.follow
    - toc.integrate
    - navigation.tabs
    - content.action.edit
  logo: assets/cldk.png
  palette:
    - primary: custom
nav:
  - Home: docs/README.md
  - Walkthrough: docs/walkthrough.md
  - API Reference: docs/api_reference.md
  - Publications: docs/publications.md
  - Contribute: docs/contribute.md

# Define some IBM colors
extra_css:
  - stylesheets/extra.css

plugins:
- search
- mkdocstrings: # see https://mkdocstrings.github.io/python/usage/
    handlers:
      python:
        options:
          allow_inspection: true
          show_source: true
          show_bases: true
          show_symbol_type_toc: true
          show_submodules: false
          show_root_toc_entry: true
          docstring_section_style: table
          inherited_members: false
          summary: true
          docstring_style: google
          show_if_no_docstring: false
          show_labels: true
          heading_level: 3
          show_symbol_type_heading: true
          show_signature: true
          show_signature_annotations: true
          members_order: source

markdown_extensions:
  - admonition
  - toc:
      toc_depth: 3
