site_name: CodeLLM-Devkit
site_description: A library for streamlined code analysis insights for CodeLLM development and deployment.
repo_url: https://github.com/IBM/codellm-devkit
repo_name: IBM/codellm-devkit
strict: false
copyright: Copyright &copy; 2024-2025 IBM

nav:
  - Home:
    - Introduction: index.md
    - Quick Start: quickstart.md
    - Installation: installing.md
    - Core Concepts: core-concepts/index.md

theme:
  name: material
  logo: assets/images/logo-white.svg
  favicon: assets/images/favicon.png
  custom_dir: docs/overrides
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
  features:
    - announce.dismiss
    - content.code.copy
    - content.tabs.link
    - navigation.indexes
    - navigation.footer
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - search.highlight
    - search.suggest
    - toc.follow

markdown_extensions:
  - admonition # callouts
  - footnotes
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify # NOTE: insiders only
        kwds:
          case: lower
  - toc:
      permalink: "#"
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - docs/overrides/.icons
  - pymdownx.arithmatex:
      generic: true

watch:
  - cldk

extra_css:
  - assets/css/theme.css
  - assets/css/mkdocstrings.css

extra_javascript:
  - assets/javascript/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  social: # render social media cards for copy+paste
    cache_dir: .cache/plugin/social/free
  search:
    lang: en
  git-revision-date-localized:
  mkdocstrings:
    handlers:
      python:
        module: cldk
        import:
          - https://docs.python.org/3/objects.inv
          - https://docs.scipy.org/doc/numpy/objects.inv
        options:
          docstring_style: sphinx
          merge_init_into_class: true
          members_order: source # sort members in the order they are defined
          show_docstring_attributes: true
          show_root_toc_entry: false
          show_source: false

extra:
  generator: false
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/IBM
      name: IBM on Twitter
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/IBM
      name: IBM on LinkedIn
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/cldk
    - icon: fontawesome/brands/github
      link: https://github.com/IBM/codellm-devkit
      name: CLDK on GitHub
    - icon: cldk/logo-white
      link: https://ibm.github.io/codellm-devkit
      name: The CLDK Library
  dd_rum:
    client_token: !ENV [ DD_RUM_CLIENT_TOKEN, blank ]
    application_id: !ENV [ DD_RUM_APPLICATION_ID, blank ]
